openapi: 3.0.1
info:
  title: "WasaPhoto"
  version: 1.0.0
  description: api for "WasaPhoto" project

components:
  schemas:
    identifier:
      title: Id
      description: identifier of an object
      type: string
      example: "1a76Vr4"
      minLength: 4
      maxLength: 10
      pattern: "^[a-zA-Z0-9_-]{4,10}$"
      readOnly: true
    Post:
      title: Post
      description: this is the post object, with an image and meta informations
      type: object
      required:
        - "photo"
        - "time"
        - "id"
      properties:
        photo:
          description: your image
          type: string
          format: binary
        id:
          $ref: "#/components/schemas/identifier"
        time:
          description: when the post was uploaded
          type: string
          format: date-time
        \#like:
          description: number of likes
          type: integer
          default: 0
          readOnly: true
        likes:
          description: list of likes of the post
          type: array
          items: 
            $ref: "#/components/schemas/Like"
          minItems: 0
          maxItems: 10000
        comments:
          description: list of comments of the post
          type: array
          items: 
            $ref: "#/components/schemas/Comment"
          minItems: 0
          maxItems: 10000
    Like:
      title: Post upvote
      description: post upvote
      type: object
      properties:
        User:
          $ref: "#/components/schemas/identifier"
        date:
          description: when this upvote was sent
          type: string
          format: date-time
    Comment:
      title: Post comment
      description: post comment
      type: object
      properties:
        User:
          $ref: "#/components/schemas/identifier"
        date:
          description: when this comment was sent
          type: string
          format: date-time
        content:
          description: user's input string
          type: string
          pattern: "^[a-zA-Z0-9_]+$"
          minLength: 1
          maxLength: 300
          example: "I wish I knew how to write an api"
    User:
      title: User
      description: this object is a single user
      type: object
      properties:
        id:
          $ref: "#/components/schemas/identifier"
        username:
          description: how the user will be recognized
          type: string
          minLength: 1
          maxLength: 25
          pattern: '.*?{1,25}$' #(.*?)
          example: "SkibidiSigma420"
        posted:
          description: list of user's post
          type: array
          items: 
            $ref: "#/components/schemas/Post/properties/id"
          minItems: 0
          maxItems: 10000
  securitySchemes:
    bearerAuth:            # arbitrary name for the security scheme
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: Use Bearer token for authentication (JWT)
  responses:
    NotFound:
      description: Content not found
      content:
        application/json:
          schema:
            type: string
            minLength: 0
            maxLength: 30
            pattern: '.*?$' #(.*?)
    OkDone:):
      description: Ok
      content:
        application/json:
          schema:
            type: string
            minLength: 0
            maxLength: 30
            pattern: '.*?$' #(.*?)
    UnauthorizedError:
      description: Access token is missing or invalid
      content:
        application/json:
          schema:
            type: string
            minLength: 0
            maxLength: 30
            pattern: '.*?$' #(.*?)
    ServerError:
      description: something went wrong, try late or never again
      content:
        application/json:
          schema:
            type: string
            minLength: 0
            maxLength: 30
            pattern: '.*?$' #(.*?)
security:
  - bearerAuth: []
             
paths:
  /session:
    post:
      tags: ["login"]
      summary: Logs in the user
      description: |-
        If the user does not exist, it will be created,
        and an identifier is returned.
        If the user exists, the user identifier is returned.
      operationId: doLogin
      requestBody:
        description: User details

        content:
          application/json:
            schema:
              description: the name string
              type: object
              properties:
                name:
                  $ref: "#/components/schemas/User/properties/username"

        required: true
      responses:
        "200":
          description: user already logged in, returned their own id
          content:
            application/json:
              schema:
                {$ref: "#/components/schemas/identifier"}
        '201':
          description: User log-in action successful
          content:
              application/json:
                schema:
                  description: you'll receive the token and uid
                  type: object
                  properties:
                    token:
                      $ref: "#/components/schemas/identifier"
                    uid:
                      $ref: "#/components/schemas/identifier"
        "500":
          description: something went wrong in the server
 
  /Images/{postId}/likes/:
    post:
        summary: place a like on the post
        description: insert a like object in the like list of the post
        operationId: likePhoto
        tags: ["like"]
        parameters:
          - name: userId
            in: header
            schema: 
              $ref: "#/components/schemas/identifier"
            required: true
          - name: postId
            in: path
            schema: 
              $ref: "#/components/schemas/identifier"
            required: true
        requestBody:
          description: like object
          required: true
          content:
            application/json:
              schema: {$ref: "#/components/schemas/Like"}
        responses:
          "201":
            description: like created
            content:
              application/json:
                schema:
                  $ref: "#/components/schemas/Like"
          "403":
            $ref: "#/components/responses/UnauthorizedError"
          "404":
            $ref: "#/components/responses/NotFound"
          "500":
            $ref: "#/components/responses/ServerError"
  /Images/{postId}/likes/{yourId}:
    delete:
      summary: delete your like on the post
      description: remove a like object in the like list of the post
      operationId: unlikePhoto
      tags: ["like"]
      parameters:
        - name: postId
          in: path
          schema: 
            $ref: "#/components/schemas/identifier"
          required: true
        - name: yourId
          in: path
          required: true
          schema:
            $ref: "#/components/schemas/identifier"
      responses:
        "200":
          $ref: "#/components/responses/OkDone:)"
        "403":
          $ref: "#/components/responses/UnauthorizedError"
        "404":
          $ref: "#/components/responses/NotFound"
        "500":
          $ref: "#/components/responses/ServerError"
  /Images/{postId}/comments/:     
    post:
      summary: place a comment on the post
      description: insert a comment object in the comment list of the post
      operationId: commentPhoto
      tags: ["comment"]
      parameters:
          - name: postId
            in: path
            schema: 
              $ref: "#/components/schemas/identifier"
            required: true
      requestBody:
        description: comment
        required: true
        content:
          application/json:
            schema: {$ref: "#/components/schemas/Comment"}
      responses:
        "201":
          $ref: "#/components/responses/OkDone:)"
        "403":
          $ref: "#/components/responses/UnauthorizedError"
        "404":
          $ref: "#/components/responses/NotFound"
        "500":
          $ref: "#/components/responses/ServerError"
  /Images/{postId}/comments/{yourId}:
    delete:
      summary: delete your comment on the post
      description: remove a comment object in the comment list of the post
      operationId: uncommentPhoto
      tags: ["comment"]
      parameters:
        - name: yourId
          in: path
          schema:
            $ref: "#/components/schemas/identifier"
          required: true
        - name: postId
          in: path
          schema: 
            $ref: "#/components/schemas/identifier"
          required: true
      responses:
        "200":
          $ref: "#/components/responses/OkDone:)"
        "403":
          $ref: "#/components/responses/UnauthorizedError"
        "404":
          $ref: "#/components/responses/NotFound"
        "500":
          $ref: "#/components/responses/ServerError"
  /Users/{userId}:
    patch:
      summary: change your username
      description: change your username, it must be valid
      operationId: setMyUserName
      tags: ["username"]
      parameters:
        - name: userId
          in: path
          required: true
          description: The id username of the user to update
          schema:
            $ref: "#/components/schemas/identifier"
      requestBody:
        description: String payload for updating the resource
        required: true
        content:
          text/plain:
            schema:
             $ref: "#/components/schemas/User/properties/username"
 
      responses:
        "200":
          $ref: "#/components/responses/OkDone:)"
        "403":
          $ref: "#/components/responses/UnauthorizedError"
        "404":
          $ref: "#/components/responses/NotFound"
        "500":
          $ref: "#/components/responses/ServerError"
  /Users/:
    get:
      summary: get a user profile
      description: | 
        receive a user profile, made of:
        - username
        - posts
        - followed and following lists
      operationId: getUserProfile
      tags: ["profile"]
      parameters:
        - name: username to find
          in: query
          required: true
          description: The name of the user to check
          schema:
            $ref: "#/components/schemas/User/properties/username"

      responses:
        "200":
          description: Successful retrieval
          content:
            application/json:
              schema: {$ref: "#/components/schemas/User"}
        "403":
          $ref: "#/components/responses/UnauthorizedError"
        "404":
          $ref: "#/components/responses/NotFound"
        "500":
          $ref: "#/components/responses/ServerError"           
  /Users/me/mystream/:
    get:
      summary: watch your friends' photos
      description: |
        receive a stream of posts, picked only from people
        you follow in anti-chronological order
      operationId: getMyStream
      tags: ["feed", "stream", "forYou", "fyp"]
      responses:
        "200":
          description: feed successfully sent
          content:
            application/json:
              schema:
                description: array of postIds to fetch after
                type: array
                items:
                  {$ref: "#/components/schemas/Post/properties/id"}
                minItems: 0
                maxItems: 20
        "403":
          $ref: "#/components/responses/UnauthorizedError"
        "404":
          $ref: "#/components/responses/NotFound"
        "500":
          $ref: "#/components/responses/ServerError"  
  /Images/:
    post:
      summary: create a new post
      description: |
        add an image to your profile, to be displayed
        in anti-chronological order
      operationId: uploadPhoto
      tags: ["post", "upload", "create"]
      requestBody:
        required: true
        description: upload your photo, with time
        content:
          multipart/form-data:
            schema: {$ref: "#/components/schemas/Post"}
            #encoding:
              #photo:
                #contentType: image/png, image/jpeg
      responses:
        "201":
          $ref: "#/components/responses/OkDone:)"
        "403":
          $ref: "#/components/responses/UnauthorizedError"
        "404":
          $ref: "#/components/responses/NotFound"
        "500":
          $ref: "#/components/responses/ServerError"
  /Images/{postId}:
    delete:
      summary: delete one of your posts
      description: |
        delete a post from your profile, 
        given its id
      operationId: deletePhoto
      tags: ["photo"]
      parameters:
        - in: path
          name: postId
          required: true
          description: Id of photo you want to delete
          schema:
            $ref: "#/components/schemas/identifier"
      responses:
        "200":
          $ref: "#/components/responses/OkDone:)"
        "401":
          $ref: '#/components/responses/UnauthorizedError'
        "403":
          $ref: "#/components/responses/UnauthorizedError"
        "404":
          $ref: "#/components/responses/NotFound"
        "500":
          $ref: "#/components/responses/ServerError"
    get:
      summary: get a post
      description: aquire a post given its id
      operationId: getPhoto
      tags: ["photo"]
      parameters:
        - in: path
          name: postId
          required: true
          description: photoId to get
          schema:
            $ref: "#/components/schemas/identifier"
      responses:
        "200":
          $ref: "#/components/responses/OkDone:)"
        "403":
          $ref: "#/components/responses/UnauthorizedError"
        "404":
          $ref: "#/components/responses/NotFound"
        "500":
          $ref: "#/components/responses/ServerError"
  /Users/me/following/{followId}:
    put:
      summary: follow a user 
      description: |
        insert a user in your list of people you follow,
        you will see Their posts 
      operationId: followUser
      tags: ["follow"]
      parameters:
        - name: followId
          in: path
          required: true
          description: uid to follow
          schema:
            $ref: "#/components/schemas/identifier" 
      requestBody:
        description: the person you want to follow
        required: true
        content:
          application/json:
            schema: {$ref: "#/components/schemas/User"}
      responses:
        "201":
          $ref: "#/components/responses/OkDone:)"
        "403":
          $ref: "#/components/responses/UnauthorizedError"
        "404":
          $ref: "#/components/responses/NotFound"
        "500":
          $ref: "#/components/responses/ServerError"
    delete:
      summary: unfollow a user 
      description: |
        delete a user in your follow list,
        you won't see their posts again
      operationId: unfollowUser
      tags: ["follow", "unfollow"]
      parameters:
        - name: followId
          in: path
          required: true
          description: uid to unfollow
          schema:
            $ref: "#/components/schemas/identifier" 
      responses:
        "200":
          $ref: "#/components/responses/OkDone:)"
        "403":
          $ref: "#/components/responses/UnauthorizedError"
        "404":
          $ref: "#/components/responses/NotFound"
        "500":
          $ref: "#/components/responses/ServerError"
  /Users/me/muted/{bannedId}:
    put:
      summary: ban a user 
      description: |
        insert a user in your list of banned people,
        they won't see your posts 
      operationId: banUser
      tags: ["muted"]
      parameters:
        - name: bannedId
          in: path
          description: Id of the user you want to ban
          required: true
          schema:
            $ref: "#/components/schemas/identifier" 
      responses:
        "201":
          $ref: "#/components/responses/OkDone:)"
        "403":
          $ref: "#/components/responses/UnauthorizedError"
        "404":
          $ref: "#/components/responses/NotFound"
        "500":
          $ref: "#/components/responses/ServerError"
    delete:
      summary: unban a banned user 
      description: |
        delete a user in your banlist,
        they will see your posts again
      operationId: unbanUser
      tags: ["muted", "unmute"]
      parameters:
        - name: bannedId
          in: path
          description: Id of the user you want to unban
          required: true
          schema:
            $ref: "#/components/schemas/identifier"
      responses:
        "200":
          $ref: "#/components/responses/OkDone:)"
        "403":
          $ref: "#/components/responses/UnauthorizedError"
        "404":
          $ref: "#/components/responses/NotFound"
        "500":
          $ref: "#/components/responses/ServerError"
  
        
      